// Drizzle schema — mirrors migrations/0001_init.sql 1:1 (Doc 04 header rule), including every
// CHECK constraint, so `drizzle-kit generate` against this file reproduces the same DDL
// (Doc 04 §8: migrations are "generated by drizzle-kit"). Two things `drizzle-kit generate`
// cannot express are appended by hand to the generated migration file afterward: the CREATE VIEW
// statements (Doc 04 §4) and the seed INSERTs (Doc 04 §7) — see the migration file's own header.
//
// Views (v_stock, v_kardex, v_price_health, v_receivables, v_liability, v_cashflow_daily,
// v_session_hours, v_waste) are defined only in the SQL migration — Drizzle's SQLite view
// support does not model window functions/partial-aggregate views well, so `core/` services
// query them via `db.all(sql\`SELECT * FROM v_x ...\`)` with a hand-written result type instead
// of a Drizzle view binding.

import { sql } from "drizzle-orm";
import {
  type AnySQLiteColumn,
  check,
  index,
  integer,
  real,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

// ============================================================================
// 1. Catalog (Doc 04 §3.1)
// ============================================================================

export const items = sqliteTable(
  "items",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull().unique(),
    kind: text("kind", { enum: ["RAW_MATERIAL", "SEMI_FINISHED", "FINISHED"] }).notNull(),
    category: text("category", {
      enum: ["INGREDIENT", "PACKAGING", "LABEL", "BAKERY", "DAIRY", "OTHER"],
    }).notNull(),
    unit: text("unit", { enum: ["G", "KG", "ML", "L", "UNIT"] }).notNull(),
    wac: real("wac").notNull().default(0),
    replacementCost: real("replacement_cost").notNull().default(0),
    replacementCostUpdatedAt: text("replacement_cost_updated_at"),
    salePrice: integer("sale_price"),
    minStockQty: integer("min_stock_qty"),
    isActive: integer("is_active").notNull().default(1),
    notes: text("notes"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => ({
    kindCheck: check(
      "items_kind_check",
      sql`${t.kind} IN ('RAW_MATERIAL','SEMI_FINISHED','FINISHED')`,
    ),
    categoryCheck: check(
      "items_category_check",
      sql`${t.category} IN ('INGREDIENT','PACKAGING','LABEL','BAKERY','DAIRY','OTHER')`,
    ),
    unitCheck: check("items_unit_check", sql`${t.unit} IN ('G','KG','ML','L','UNIT')`),
  }),
);

export const itemAliases = sqliteTable("item_aliases", {
  id: text("id").primaryKey(),
  itemId: text("item_id")
    .notNull()
    .references(() => items.id, { onDelete: "cascade" }),
  // Doc 04 §3.1 specifies `COLLATE NOCASE` for case-insensitive alias matching. This drizzle-orm
  // version's sqlite text() builder has no `.collate()` modifier, so it is hand-patched onto this
  // column directly in migrations/0001_init.sql — if you add drizzle-kit-generated migrations
  // later, verify that patch survives (drizzle-kit's snapshot has no record of it).
  alias: text("alias").notNull().unique(),
});

export const recipes = sqliteTable(
  "recipes",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    outputItemId: text("output_item_id")
      .notNull()
      .references(() => items.id, { onDelete: "restrict" }),
    expectedYieldQty: integer("expected_yield_qty").notNull(),
    estLaborMin: integer("est_labor_min"),
    isDefault: integer("is_default").notNull().default(0),
    isActive: integer("is_active").notNull().default(1),
    notes: text("notes"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => ({
    // Partial unique index: one default recipe per output item (Doc 04 §3.1).
    uxDefault: uniqueIndex("ux_recipes_default")
      .on(t.outputItemId)
      .where(sql`${t.isDefault} = 1 AND ${t.isActive} = 1`),
  }),
);

export const recipeLines = sqliteTable(
  "recipe_lines",
  {
    id: text("id").primaryKey(),
    recipeId: text("recipe_id")
      .notNull()
      .references(() => recipes.id, { onDelete: "cascade" }),
    itemId: text("item_id")
      .notNull()
      .references(() => items.id, { onDelete: "restrict" }),
    qty: integer("qty").notNull(),
  },
  (t) => ({
    qtyCheck: check("recipe_lines_qty_check", sql`${t.qty} > 0`),
  }),
);

export const priceHistory = sqliteTable("price_history", {
  id: text("id").primaryKey(),
  itemId: text("item_id")
    .notNull()
    .references(() => items.id, { onDelete: "restrict" }),
  price: integer("price").notNull(),
  effectiveFrom: text("effective_from").notNull(),
  note: text("note"),
});

// ============================================================================
// 2. Sessions (Doc 04 §3.2)
// ============================================================================

export const sessions = sqliteTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    type: text("type", {
      enum: ["PRODUCTION", "PURCHASE_TRIP", "DELIVERY_RUN", "ADMIN", "OTHER"],
    }).notNull(),
    businessDate: text("business_date").notNull(),
    startedAt: text("started_at"),
    endedAt: text("ended_at"),
    durationMin: integer("duration_min"),
    status: text("status", { enum: ["OPEN", "CLOSED"] })
      .notNull()
      .default("OPEN"),
    notes: text("notes"),
    deletedAt: text("deleted_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => ({
    typeCheck: check(
      "sessions_type_check",
      sql`${t.type} IN ('PRODUCTION','PURCHASE_TRIP','DELIVERY_RUN','ADMIN','OTHER')`,
    ),
    statusCheck: check("sessions_status_check", sql`${t.status} IN ('OPEN','CLOSED')`),
  }),
);

export const sessionCosts = sqliteTable(
  "session_costs",
  {
    id: text("id").primaryKey(),
    sessionId: text("session_id")
      .notNull()
      .references(() => sessions.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    amount: integer("amount").notNull(),
    isEstimate: integer("is_estimate").notNull().default(0),
    // Forward reference — financial_accounts is declared later in this file (Doc 04 §3.4).
    accountId: text("account_id").references((): AnySQLiteColumn => financialAccounts.id, {
      onDelete: "restrict",
    }),
  },
  (t) => ({
    amountCheck: check("session_costs_amount_check", sql`${t.amount} >= 0`),
  }),
);

// ============================================================================
// 3. Business events (Doc 04 §3.3)
// ============================================================================

export const purchases = sqliteTable("purchases", {
  id: text("id").primaryKey(),
  occurredAt: text("occurred_at").notNull(),
  businessDate: text("business_date").notNull(),
  supplierName: text("supplier_name"),
  sessionId: text("session_id").references(() => sessions.id, { onDelete: "restrict" }),
  // Forward reference — financial_accounts is declared later (Doc 04 §3.4).
  accountId: text("account_id")
    .notNull()
    .references((): AnySQLiteColumn => financialAccounts.id, { onDelete: "restrict" }),
  total: integer("total").notNull(),
  receiptPhotoKey: text("receipt_photo_key"),
  notes: text("notes"),
  deletedAt: text("deleted_at"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const purchaseLines = sqliteTable(
  "purchase_lines",
  {
    id: text("id").primaryKey(),
    purchaseId: text("purchase_id")
      .notNull()
      .references(() => purchases.id, { onDelete: "cascade" }),
    itemId: text("item_id")
      .notNull()
      .references(() => items.id, { onDelete: "restrict" }),
    qty: integer("qty").notNull(),
    lineTotal: integer("line_total").notNull(),
  },
  (t) => ({
    qtyCheck: check("purchase_lines_qty_check", sql`${t.qty} > 0`),
    lineTotalCheck: check("purchase_lines_line_total_check", sql`${t.lineTotal} >= 0`),
  }),
);

export const productionRuns = sqliteTable(
  "production_runs",
  {
    id: text("id").primaryKey(),
    occurredAt: text("occurred_at").notNull(),
    businessDate: text("business_date").notNull(),
    recipeId: text("recipe_id")
      .notNull()
      .references(() => recipes.id, { onDelete: "restrict" }),
    sessionId: text("session_id").references(() => sessions.id, { onDelete: "restrict" }),
    // Forward reference — custom_orders is declared later (Doc 04 §3.3, O-4).
    customOrderId: text("custom_order_id").references((): AnySQLiteColumn => customOrders.id, {
      onDelete: "restrict",
    }),
    batches: real("batches").notNull(),
    outputItemId: text("output_item_id")
      .notNull()
      .references(() => items.id, { onDelete: "restrict" }),
    actualOutputQty: integer("actual_output_qty").notNull(),
    indirectCost: integer("indirect_cost").notNull().default(0),
    allocatedSessionCost: integer("allocated_session_cost").notNull().default(0),
    directCost: integer("direct_cost").notNull().default(0),
    totalCost: integer("total_cost").notNull().default(0),
    notes: text("notes"),
    deletedAt: text("deleted_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => ({
    batchesCheck: check("production_runs_batches_check", sql`${t.batches} > 0`),
    outputQtyCheck: check("production_runs_actual_output_qty_check", sql`${t.actualOutputQty} > 0`),
  }),
);

export const productionConsumptions = sqliteTable(
  "production_consumptions",
  {
    id: text("id").primaryKey(),
    productionRunId: text("production_run_id")
      .notNull()
      .references(() => productionRuns.id, { onDelete: "cascade" }),
    itemId: text("item_id")
      .notNull()
      .references(() => items.id, { onDelete: "restrict" }),
    qty: integer("qty").notNull(),
    unitCostSnapshot: real("unit_cost_snapshot").notNull(),
  },
  (t) => ({
    qtyCheck: check("production_consumptions_qty_check", sql`${t.qty} > 0`),
  }),
);

export const customers = sqliteTable("customers", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  phone: text("phone"),
  notes: text("notes"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const sales = sqliteTable(
  "sales",
  {
    id: text("id").primaryKey(),
    occurredAt: text("occurred_at").notNull(),
    businessDate: text("business_date").notNull(),
    channel: text("channel", { enum: ["CATALOG", "CUSTOM_ORDER"] }).notNull(),
    // Forward reference — custom_orders is declared later (circular FK, Doc 04 §3.3).
    customOrderId: text("custom_order_id").references((): AnySQLiteColumn => customOrders.id, {
      onDelete: "restrict",
    }),
    customerId: text("customer_id").references(() => customers.id, { onDelete: "restrict" }),
    sessionId: text("session_id").references(() => sessions.id, { onDelete: "restrict" }),
    total: integer("total").notNull(),
    paymentStatus: text("payment_status", { enum: ["PAID", "ON_CREDIT"] }).notNull(),
    paidAt: text("paid_at"),
    paymentMethod: text("payment_method", { enum: ["CASH", "BANK_QR"] }),
    // Forward reference — financial_accounts is declared later (Doc 04 §3.4).
    accountId: text("account_id").references((): AnySQLiteColumn => financialAccounts.id, {
      onDelete: "restrict",
    }),
    notes: text("notes"),
    deletedAt: text("deleted_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => ({
    channelCheck: check("sales_channel_check", sql`${t.channel} IN ('CATALOG','CUSTOM_ORDER')`),
    paymentStatusCheck: check(
      "sales_payment_status_check",
      sql`${t.paymentStatus} IN ('PAID','ON_CREDIT')`,
    ),
    paymentMethodCheck: check(
      "sales_payment_method_check",
      sql`${t.paymentMethod} IN ('CASH','BANK_QR')`,
    ),
    ixDate: index("ix_sales_date").on(t.businessDate),
    ixStatus: index("ix_sales_status")
      .on(t.paymentStatus)
      .where(sql`${t.paymentStatus} = 'ON_CREDIT'`),
  }),
);

export const saleLines = sqliteTable(
  "sale_lines",
  {
    id: text("id").primaryKey(),
    saleId: text("sale_id")
      .notNull()
      .references(() => sales.id, { onDelete: "cascade" }),
    itemId: text("item_id")
      .notNull()
      .references(() => items.id, { onDelete: "restrict" }),
    qty: integer("qty").notNull(),
    unitPrice: integer("unit_price").notNull(),
    unitCostSnapshot: real("unit_cost_snapshot").notNull(),
  },
  (t) => ({
    qtyCheck: check("sale_lines_qty_check", sql`${t.qty} > 0`),
  }),
);

export const customOrders = sqliteTable(
  "custom_orders",
  {
    id: text("id").primaryKey(),
    status: text("status", {
      enum: ["QUOTING", "CONFIRMED", "IN_PRODUCTION", "READY", "DELIVERED", "CANCELLED"],
    }).notNull(),
    customerId: text("customer_id")
      .notNull()
      .references(() => customers.id, { onDelete: "restrict" }),
    description: text("description").notNull(),
    agreedTotal: integer("agreed_total"),
    depositRequired: integer("deposit_required"),
    depositPaid: integer("deposit_paid").notNull().default(0),
    // Forward reference — financial_transactions is declared later (Doc 04 §3.4).
    depositTxId: text("deposit_tx_id").references((): AnySQLiteColumn => financialTransactions.id, {
      onDelete: "restrict",
    }),
    deliveryDate: text("delivery_date"),
    deliveryPlace: text("delivery_place"),
    // Backward reference — sales is declared above, no forward-ref annotation needed.
    saleId: text("sale_id").references(() => sales.id, { onDelete: "restrict" }),
    cancelResolution: text("cancel_resolution", { enum: ["REFUND", "FORFEIT"] }),
    notes: text("notes"),
    deletedAt: text("deleted_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => ({
    statusCheck: check(
      "custom_orders_status_check",
      sql`${t.status} IN ('QUOTING','CONFIRMED','IN_PRODUCTION','READY','DELIVERED','CANCELLED')`,
    ),
    cancelResolutionCheck: check(
      "custom_orders_cancel_resolution_check",
      sql`${t.cancelResolution} IN ('REFUND','FORFEIT')`,
    ),
    ixStatusDate: index("ix_orders_status_date").on(t.status, t.deliveryDate),
  }),
);

export const customOrderLines = sqliteTable("custom_order_lines", {
  id: text("id").primaryKey(),
  customOrderId: text("custom_order_id")
    .notNull()
    .references(() => customOrders.id, { onDelete: "cascade" }),
  itemId: text("item_id").references(() => items.id, { onDelete: "restrict" }),
  description: text("description"),
  qty: integer("qty").notNull().default(1000),
  lineTotal: integer("line_total"),
});

export const stockExits = sqliteTable(
  "stock_exits",
  {
    id: text("id").primaryKey(),
    occurredAt: text("occurred_at").notNull(),
    businessDate: text("business_date").notNull(),
    itemId: text("item_id")
      .notNull()
      .references(() => items.id, { onDelete: "restrict" }),
    qty: integer("qty").notNull(),
    reason: text("reason", {
      enum: ["WASTE", "SELF_CONSUMPTION", "GIFT_SAMPLE", "SPOILAGE", "OTHER"],
    }).notNull(),
    unitCostSnapshot: real("unit_cost_snapshot").notNull(),
    sessionId: text("session_id").references(() => sessions.id, { onDelete: "restrict" }),
    notes: text("notes"),
    deletedAt: text("deleted_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => ({
    qtyCheck: check("stock_exits_qty_check", sql`${t.qty} > 0`),
    reasonCheck: check(
      "stock_exits_reason_check",
      sql`${t.reason} IN ('WASTE','SELF_CONSUMPTION','GIFT_SAMPLE','SPOILAGE','OTHER')`,
    ),
    ixDate: index("ix_exits_date").on(t.businessDate),
  }),
);

export const inventoryCounts = sqliteTable(
  "inventory_counts",
  {
    id: text("id").primaryKey(),
    occurredAt: text("occurred_at").notNull(),
    businessDate: text("business_date").notNull(),
    status: text("status", { enum: ["DRAFT", "COMMITTED"] })
      .notNull()
      .default("DRAFT"),
    notes: text("notes"),
    deletedAt: text("deleted_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => ({
    statusCheck: check("inventory_counts_status_check", sql`${t.status} IN ('DRAFT','COMMITTED')`),
  }),
);

export const inventoryCountLines = sqliteTable(
  "inventory_count_lines",
  {
    id: text("id").primaryKey(),
    countId: text("count_id")
      .notNull()
      .references(() => inventoryCounts.id, { onDelete: "cascade" }),
    itemId: text("item_id")
      .notNull()
      .references(() => items.id, { onDelete: "restrict" }),
    expectedQty: integer("expected_qty").notNull(),
    countedQty: integer("counted_qty").notNull(),
  },
  (t) => ({
    uxCountItem: uniqueIndex("ux_inventory_count_lines_count_item").on(t.countId, t.itemId),
  }),
);

// ============================================================================
// 4. Derived ledgers (Doc 04 §3.4)
// ============================================================================

export const stockMovements = sqliteTable(
  "stock_movements",
  {
    id: text("id").primaryKey(),
    occurredAt: text("occurred_at").notNull(),
    businessDate: text("business_date").notNull(),
    itemId: text("item_id")
      .notNull()
      .references(() => items.id, { onDelete: "restrict" }),
    type: text("type", {
      enum: ["PURCHASE_IN", "PRODUCTION_IN", "PRODUCTION_OUT", "SALE_OUT", "EXIT_OUT", "ADJUST"],
    }).notNull(),
    qty: integer("qty").notNull(),
    unitCost: real("unit_cost").notNull(),
    totalCost: integer("total_cost").notNull(),
    sourceEventType: text("source_event_type").notNull(),
    sourceEventId: text("source_event_id").notNull(),
    createdAt: text("created_at").notNull(),
  },
  (t) => ({
    typeCheck: check(
      "stock_movements_type_check",
      sql`${t.type} IN ('PURCHASE_IN','PRODUCTION_IN','PRODUCTION_OUT','SALE_OUT','EXIT_OUT','ADJUST')`,
    ),
    ixItemDate: index("ix_movements_item_date").on(t.itemId, t.businessDate),
    ixSource: index("ix_movements_source").on(t.sourceEventType, t.sourceEventId),
  }),
);

export const itemStock = sqliteTable("item_stock", {
  itemId: text("item_id")
    .primaryKey()
    .references(() => items.id, { onDelete: "restrict" }),
  qtyOnHand: integer("qty_on_hand").notNull().default(0),
  negativeSince: text("negative_since"),
  updatedAt: text("updated_at").notNull(),
});

export const financialAccounts = sqliteTable(
  "financial_accounts",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    type: text("type", { enum: ["BANK", "CASH"] }).notNull(),
    openingBalance: integer("opening_balance").notNull().default(0),
    balance: integer("balance").notNull().default(0),
    isActive: integer("is_active").notNull().default(1),
  },
  (t) => ({
    typeCheck: check("financial_accounts_type_check", sql`${t.type} IN ('BANK','CASH')`),
  }),
);

export const financialTransactions = sqliteTable(
  "financial_transactions",
  {
    id: text("id").primaryKey(),
    occurredAt: text("occurred_at").notNull(),
    businessDate: text("business_date").notNull(),
    accountId: text("account_id")
      .notNull()
      .references(() => financialAccounts.id, { onDelete: "restrict" }),
    type: text("type", { enum: ["INCOME", "EXPENSE", "TRANSFER_IN", "TRANSFER_OUT"] }).notNull(),
    category: text("category", {
      enum: [
        "SALE",
        "ORDER_DEPOSIT",
        "ORDER_BALANCE",
        "DEBT_COLLECTION",
        "OTHER_INCOME",
        "SUPPLY_PURCHASE",
        "OPERATING_EXPENSE",
        "EQUIPMENT",
        "DEPOSIT_REFUND",
        "OWNER_WITHDRAWAL",
        "TRANSFER",
        "OTHER_EXPENSE",
      ],
    }).notNull(),
    amount: integer("amount").notNull(),
    counterpartTxId: text("counterpart_tx_id").references(
      (): AnySQLiteColumn => financialTransactions.id,
      { onDelete: "restrict" },
    ),
    sourceEventType: text("source_event_type"),
    sourceEventId: text("source_event_id"),
    description: text("description"),
    deletedAt: text("deleted_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => ({
    typeCheck: check(
      "financial_transactions_type_check",
      sql`${t.type} IN ('INCOME','EXPENSE','TRANSFER_IN','TRANSFER_OUT')`,
    ),
    categoryCheck: check(
      "financial_transactions_category_check",
      sql`${t.category} IN ('SALE','ORDER_DEPOSIT','ORDER_BALANCE','DEBT_COLLECTION','OTHER_INCOME','SUPPLY_PURCHASE','OPERATING_EXPENSE','EQUIPMENT','DEPOSIT_REFUND','OWNER_WITHDRAWAL','TRANSFER','OTHER_EXPENSE')`,
    ),
    amountCheck: check("financial_transactions_amount_check", sql`${t.amount} > 0`),
    ixAccountDate: index("ix_tx_account_date").on(t.accountId, t.businessDate),
    ixSource: index("ix_tx_source").on(t.sourceEventType, t.sourceEventId),
    ixCategoryDate: index("ix_tx_category_date").on(t.category, t.businessDate),
  }),
);

// ============================================================================
// 5. System & observability (Doc 04 §3.5)
// ============================================================================

export const appSettings = sqliteTable("app_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
});

export const dailySnapshots = sqliteTable("daily_snapshots", {
  businessDate: text("business_date").primaryKey(),
  stockValue: integer("stock_value").notNull(),
  bankBalance: integer("bank_balance").notNull(),
  cashBalance: integer("cash_balance").notNull(),
  accountsReceivable: integer("accounts_receivable").notNull(),
  customerDeposits: integer("customer_deposits").notNull(),
  createdAt: text("created_at").notNull(),
});

export const auditLog = sqliteTable(
  "audit_log",
  {
    id: text("id").primaryKey(),
    at: text("at").notNull(),
    actor: text("actor", {
      enum: ["OWNER_WEB", "OWNER_TELEGRAM", "ASSISTANT", "SYSTEM"],
    }).notNull(),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    beforeJson: text("before_json"),
    afterJson: text("after_json"),
  },
  (t) => ({
    actorCheck: check(
      "audit_log_actor_check",
      sql`${t.actor} IN ('OWNER_WEB','OWNER_TELEGRAM','ASSISTANT','SYSTEM')`,
    ),
    ixEntity: index("ix_audit_entity").on(t.entityType, t.entityId),
  }),
);

export const assistantInteractions = sqliteTable(
  "assistant_interactions",
  {
    id: text("id").primaryKey(),
    at: text("at").notNull(),
    channel: text("channel", { enum: ["TELEGRAM", "WEB"] }).notNull(),
    pipeline: text("pipeline", { enum: ["CAPTURE", "QUERY"] }).notNull(),
    userInput: text("user_input").notNull(),
    model: text("model").notNull(),
    toolCallsJson: text("tool_calls_json"),
    draftJson: text("draft_json"),
    outcome: text("outcome", {
      enum: ["ACCEPTED", "EDITED", "REJECTED", "ANSWERED", "FAILED"],
    }),
    editedFieldsJson: text("edited_fields_json"),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    latencyMs: integer("latency_ms"),
    error: text("error"),
  },
  (t) => ({
    channelCheck: check(
      "assistant_interactions_channel_check",
      sql`${t.channel} IN ('TELEGRAM','WEB')`,
    ),
    pipelineCheck: check(
      "assistant_interactions_pipeline_check",
      sql`${t.pipeline} IN ('CAPTURE','QUERY')`,
    ),
    outcomeCheck: check(
      "assistant_interactions_outcome_check",
      sql`${t.outcome} IN ('ACCEPTED','EDITED','REJECTED','ANSWERED','FAILED')`,
    ),
    ixAt: index("ix_ai_at").on(t.at),
  }),
);

export const jobRuns = sqliteTable("job_runs", {
  id: text("id").primaryKey(),
  job: text("job").notNull(),
  startedAt: text("started_at").notNull(),
  finishedAt: text("finished_at"),
  ok: integer("ok"),
  detail: text("detail"),
});

export const telegramUpdates = sqliteTable("telegram_updates", {
  updateId: integer("update_id").primaryKey(),
  at: text("at").notNull(),
});

export const idempotencyKeys = sqliteTable("idempotency_keys", {
  key: text("key").primaryKey(),
  at: text("at").notNull(),
  responseJson: text("response_json"),
});

export const pendingDrafts = sqliteTable("pending_drafts", {
  chatId: text("chat_id").primaryKey(),
  draftJson: text("draft_json").notNull(),
  interactionId: text("interaction_id").references(() => assistantInteractions.id, {
    onDelete: "restrict",
  }),
  expiresAt: text("expires_at").notNull(),
});
